export const LOAD_MEDIA_START = 'LOAD_MEDIA_START';
export const LOAD_MEDIA_FAIL = 'LOAD_MEDIA_FAIL';
export const LOAD_MEDIA_SUCESS = 'LOAD_MEDIA_SUCESS';
export const ADD_MEDIA_SUCESS = 'ADD_MEDIA_SUCESS';

